#!/usr/bin/env python3
"""
===============================================================================
ANALYSIS 2: NEW ENTRANTS SLOT COVERAGE AND 50% RULE COMPLIANCE
===============================================================================

Goal:
    Compute new entrants' slot coverage for Summer 2019 (S19) season and verify
    compliance with the EU's 50% slot allocation rule for new entrants.

EU Regulation:
    Under EU slot regulations, at least 50% of newly available slots at
    coordinated airports must be allocated to new entrants. This analysis
    verifies compliance with this regulatory requirement.

Output:
    - Result_2/new_entrants_coverage_s19_50_percent_rule.csv
    - Contains: Airport Code, Slots Available, Slots Taken by New Entrants,
      Percentage Taken (rounded to 2 decimal places)

Business Context:
    Post-Air Berlin collapse, significant slot capacity became available.
    This analysis examines whether new entrants received adequate access
    to these slots, or if established carriers (particularly Lufthansa)
    dominated the redistribution.

===============================================================================
"""

import os
import csv
import pandas as pd

# ============================================================================
# CONFIGURATION
# ============================================================================

# Slot pool data for Summer 2019 (S19) season
# Represents newly available slots at each coordinated German airport
# Source: Airport coordination data for S19 season
AIRPORT_AND_SLOTPOOL_S19 = [
    {"airport":"DUS", "slotpool": 23981},  # Düsseldorf: Largest slot pool
    {"airport":"FRA", "slotpool": 12},     # Frankfurt: Very limited availability
    {"airport":"HAM", "slotpool": 3016},   # Hamburg
    {"airport":"MUC", "slotpool": 11249},  # Munich: Second-largest pool
    {"airport":"STR", "slotpool": 266},    # Stuttgart
    {"airport":"TXL", "slotpool": 0}       # Berlin-Tegel: No new slots available
]

# Input directory containing Analysis 1 results
Result1_DIR = "Result1"

# Output file path
OUTPUT_CSV = "Result2/new_entrants_coverage_s19_50_percent_rule.csv"

# Analysis parameters
SEASON_COL = "S19"              # Focus season: Summer 2019
TARGET_GROUP = "new_entrants"   # Group to analyze

# ============================================================================
# DATA EXTRACTION FUNCTIONS
# ============================================================================

def read_new_entrants_s19(airport_code, qdir=Result1_DIR):
    """
    Read new entrants' S19 slot allocation from Result1 airport CSV files.

    Args:
        airport_code (str): Three-letter airport IATA code
        qdir (str): Directory containing Result1 CSV files

    Returns:
        tuple: (slots_count, status_message)
            - slots_count (int): Number of slots allocated to new entrants
            - status_message (str): Processing status ("ok" or error description)

    Process:
        1. Load the airport CSV generated by Analysis 1
        2. Find the 'new_entrants' row
        3. Extract the S19 column value
        4. Parse and return as integer

    Error Handling:
        Returns (0, error_message) if:
        - File doesn't exist
        - new_entrants row is missing
        - S19 column is not found
        - Value cannot be parsed as integer
    """
    path = os.path.join(qdir, f"{airport_code}.csv")

    # Check if file exists
    if not os.path.isfile(path):
        return 0, f"missing file: {path}"

    try:
        df = pd.read_csv(path, dtype=str)
    except Exception as e:
        return 0, f"read error: {e}"

    # Normalize column names (remove leading/trailing whitespace)
    df.columns = [c.strip() for c in df.columns]

    # Find the GROUP column (may have different names)
    group_col = None
    for c in df.columns:
        if c.strip().lower() == "group":
            group_col = c
            break

    # If no explicit GROUP column, use first column as index
    if group_col is None:
        group_col = df.columns[0]

    # Locate the 'new_entrants' row (case-insensitive match)
    mask = df[group_col].astype(str).str.strip().str.lower() == TARGET_GROUP.lower()
    if not mask.any():
        return 0, f"no '{TARGET_GROUP}' row in {path}"

    row = df[mask].iloc[0]

    # Find S19 column (exact match or prefix match)
    s19_col = None
    for c in df.columns:
        if c.strip().upper() == SEASON_COL.upper():
            s19_col = c
            break

    # Try prefix match if exact match not found (e.g., "S19 Departures")
    if s19_col is None:
        for c in df.columns:
            if c.strip().upper().startswith(SEASON_COL.upper()):
                s19_col = c
                break

    if s19_col is None:
        return 0, f"no '{SEASON_COL}' column in {path}"

    # Extract raw value
    raw = row.get(s19_col, "")
    if pd.isna(raw) or str(raw).strip() == "":
        return 0, f"empty S19 for {TARGET_GROUP} in {path}"

    # Parse integer robustly (handle commas, decimal points, whitespace)
    try:
        parsed = int(float(str(raw).replace(",", "").strip()))
    except Exception:
        parsed = 0

    return parsed, "ok"

# ============================================================================
# MAIN ANALYSIS FUNCTION
# ============================================================================

def main():
    """
    Main execution function: Compute new entrants coverage and 50% rule compliance.

    Process:
        1. For each airport, read slot pool size and new entrant allocation
        2. Calculate percentage of slot pool taken by new entrants
        3. Generate compliance report CSV
        4. Print diagnostic information

    Output Format:
        CSV with columns:
        - Airport Code: Three-letter IATA code
        - Slots available: Total slots in the S19 slot pool
        - Slots taken by new_entrants: Slots allocated to new entrants
        - Pct_taken_by_new_entrants: Percentage (0-100), rounded to 2 decimals

    50% Rule Interpretation:
        Airports should allocate ≥50% of available slots to new entrants.
        Values below 50% may indicate regulatory non-compliance or market
        concentration favoring incumbent carriers.
    """
    out_rows = []
    notes = []

    # Process each airport
    for entry in AIRPORT_AND_SLOTPOOL_S19:
        airport = entry.get("airport")
        slotpool = entry.get("slotpool", 0) or 0

        # Read new entrants' slot allocation from Analysis 1 results
        new_taken, note = read_new_entrants_s19(airport)
        notes.append((airport, note))

        # Calculate percentage (avoid division by zero)
        if slotpool == 0:
            pct = 0.0
        else:
            pct = (new_taken / float(slotpool)) * 100.0

        # Build output row
        out_rows.append({
            "Airport Code": airport,
            "Slots available": slotpool,
            "Slots taken by new_entrants": new_taken,
            "Pct_taken_by_new_entrants": f"{pct:.2f}"
        })

    # Create output DataFrame with specified column order
    df_out = pd.DataFrame(out_rows, columns=[
        "Airport Code",
        "Slots available",
        "Slots taken by new_entrants",
        "Pct_taken_by_new_entrants"
    ])

    # Ensure output directory exists
    os.makedirs(os.path.dirname(OUTPUT_CSV), exist_ok=True)

    # Write results to CSV
    df_out.to_csv(OUTPUT_CSV, index=False)
    print(f"Wrote: {OUTPUT_CSV}")

    # Print diagnostic information
    print("\nDiagnostics / notes:")
    for a, n in notes:
        print(f"  {a}: {n}")

    # Print summary analysis
    print("\n" + "="*80)
    print("50% RULE COMPLIANCE SUMMARY")
    print("="*80)
    for _, row in df_out.iterrows():
        airport = row["Airport Code"]
        slots_avail = row["Slots available"]
        pct = float(row["Pct_taken_by_new_entrants"])

        if slots_avail == 0:
            status = "N/A (no slots available)"
        elif pct >= 50.0:
            status = "✓ COMPLIANT"
        else:
            status = "✗ NON-COMPLIANT"

        print(f"{airport}: {pct:.2f}% allocated to new entrants - {status}")
    print("="*80)

# ============================================================================
# SCRIPT EXECUTION
# ============================================================================

if __name__ == "__main__":
    print("="*80)
    print("ANALYSIS 2: NEW ENTRANTS SLOT COVERAGE & 50% RULE COMPLIANCE")
    print("="*80)
    print()
    print("Analyzing S19 (Summer 2019) slot allocation to new entrants...")
    print("Evaluating compliance with EU 50% allocation requirement...")
    print()

    main()
